### ISSUE TITLE
Interesting! 

### ISSUE THREAD

**Issue by Ni-Chen** [zhaoguangyuan123/Differentiable-design-of-discrete-optics-with-gumbel-softmax-trick#2]
Interesting! 
What's the advantages of utilizing "Differentiable-design" for the DOE?

**Comment by zhaoguangyuan123** [comment]
Thank you,

I assume you know the deep optics. The advantages here are the same with that. 

As for specific usage of this repo, this repo is part of our on-going project and code here is useful under specific settings. 
If you would like a follow up, will keep you updated once the paper is out. 

Best,
Guangyuan

**Comment by zhaoguangyuan123** [comment]
> Interesting! What's the advantages of utilizing "Differentiable-design" for the DOE?

https://github.com/Neural-Litho/Neural_Lithography

Hi Ni,

We used the repo here our Recent work Neural Litho.

Best,
Guangyuan
